- .gitignore
- CONTRIBUTING.md
- LICENSE.txt
- NOTICE.txt
- README.md
- SECURITY.md
Introduces the initial set of compliance files for the repo.
> Initial compliance files for repo

- .gitignore
- .verrazzano-development-version
- Jenkinsfile
- Makefile
- make/retry.mk
- module-operator/Makefile
- module-operator/tools/scripts/generate_chart_artifacts.sh
Create and publish module operator images, and create operator manifest and helm chart build artifacts.
> VZ-9388.  Initial build pipeline to build and push monitoring operator images

- calico-operator/lifecycle-actions/handlers/factory/factory.go
- calico-operator/lifecycle-actions/handlers/install/install_handler.go
- calico-operator/main.go
- common/lifecycle-actions/handlers/install/install_handler.go
Add calico handler stub to demonstrate how to override action handlers and do calico specific logic.
>  VZ-9379 add calico handler

- calico-operator/lifecycle-actions/handlers/factory/factory.go
- common/lifecycle-actions/handlers/factory/factory.go
- common/lifecycle-actions/handlers/update/update_handler.go
- common/lifecycle-actions/handlers/upgrade/upgrade_handler.go
- module-operator/apis/platform/v1alpha1/modulelifecycle_states.go
Add handler stubs for update and upgrade
> VZ-9379 update handler stubs

- calico-operator/manifests/charts/verrazzano-calico-operator/templates/serviceaccount.yaml
- helm-operator/manifests/charts/verrazzano-helm-operator/templates/serviceaccount.yaml
- module-operator/manifests/charts/verrazzano-module-operator/templates/serviceaccount.yaml
Fixes a typo in the ServiceAccount manifests in the helm charts.
> Fix SA manifests

- calico-operator/main.go
- helm-operator/main.go
Add scheme so that configmap and secret can be accessed via controller runtime.
> Add scheme so that configmap and secret can be accessed

- ccm-operator/Dockerfile
- ccm-operator/Makefile
- ccm-operator/PROJECT
- ccm-operator/internal/config/config.go
- ccm-operator/internal/config/config_test.go
- ccm-operator/lifecycle-actions/handlers/factory/factory.go
- ccm-operator/lifecycle-actions/handlers/install/install_handler.go
- ccm-operator/main.go
- ccm-operator/manifests/charts/verrazzano-calico-operator/.helmignore
- ccm-operator/manifests/charts/verrazzano-calico-operator/Chart.yaml
- ccm-operator/manifests/charts/verrazzano-calico-operator/templates/_helpers.tpl
- ccm-operator/manifests/charts/verrazzano-calico-operator/templates/clusterrolebinding.yaml
- ccm-operator/manifests/charts/verrazzano-calico-operator/templates/deployment.yaml
- ccm-operator/manifests/charts/verrazzano-calico-operator/templates/namespace.yaml
- ccm-operator/manifests/charts/verrazzano-calico-operator/templates/service.yaml
- ccm-operator/manifests/charts/verrazzano-calico-operator/templates/serviceaccount.yaml
- ccm-operator/manifests/charts/verrazzano-calico-operator/values.yaml
- ccm-operator/manifests/config/scripts/run.sh
- module-operator/apis/platform/v1alpha1/modulelifecycle_types.go
Added oci-ccm lifecycle operator.
> VZ-9362 Add oci-ccm lifecycle operator

- module-operator/apis/platform/v1alpha1/module_types.go
- module-operator/apis/platform/v1alpha1/modulelifecycle_states.go
- module-operator/controllers/module/statemachine.go
- module-operator/controllers/module/status.go
- module-operator/main.go
Start the calico controller, ccm controller, helm controller, and module controller in the module operator.
Also update the module status.
> VZ-9350 run all controllers in module-operator and update the module status

- module-operator/controllers/module/chartutil.go
- module-operator/controllers/module/handlers/common/basehandler.go
pass overrides from module CR to modulelifecycle CR
minor renaming vars.
> VZ-9350 pass overrides from module to modulelifecycle

- module-operator/Dockerfile
- module-operator/internal/config/config.go
- module-operator/internal/config/config_test.go
- module-operator/main.go
- module-operator/manifests/charts/verrazzano-module-operator/values.yaml
copy manifest directory to image
> VZ-9350 copy manifests to image

- module-operator/controllers/module/handlers/common/basehandler.go
- module-operator/controllers/module/handlers/install/install_handler.go
- module-operator/controllers/module/handlers/uninstall/uninstall_handler.go
- module-operator/controllers/module/handlers/update/update_handler.go
- module-operator/controllers/module/handlers/upgrade/upgrade_handler.go
Overriden GetStatusConditions function for install/uninstall/update/upgrade
> Updated the GetStatusConditions function for module-operator

- module-operator/manifests/charts/verrazzano-module-operator/templates/deployment.yaml
- module-operator/manifests/charts/verrazzano-module-operator/values.yaml
Add tolerations and hostnetwork to module-operator chart override.
> VZ-9350 add tolerations and hostnetwork

- module-operator/controllers/module/chartutil.go
Change ccm chart name in module-operator reconciler
> change ccm chart name in module-operator  reconciler

- common/controllers/base/statemachine/statemachine.go
- common/controllers/base/statemachine/statemachine_test.go
- common/controllers/base/statemachine/tracker.go
- common/controllers/base/statemachine/tracker_test.go
> VZ-9401 state machine unit tests

- module-operator/PROJECT
- module-operator/controllers/module/finalizer.go
- module-operator/controllers/module/handlers/common/basehandler.go
- module-operator/controllers/module/handlers/common/moduleaction_cr.go
- module-operator/controllers/moduleaction/finalizer.go
- module-operator/controllers/moduleaction/handlers/calico/factory/factory.go
- module-operator/controllers/moduleaction/handlers/helm/factory/factory.go
- module-operator/controllers/moduleaction/handlers/ociccm/factory/factory.go
- module-operator/controllers/moduleaction/manager.go
- module-operator/controllers/moduleaction/reconciler_test.go
- module-operator/internal/handlerspi/moduleaction_handler_spi.go
- module-operator/internal/statemachine/statemachine.go
- module-operator/internal/statemachine/statemachine_test.go
- module-operator/internal/statemachine/tracker_test.go
- module-operator/main.go
Change state machine to use the term work instead of action.
> VZ-9604 more cleanup related to ModuleAction name change, plus state machine action name to work

- module-operator/controllers/module/handlers/helm/install/install_handler.go
- module-operator/controllers/module/handlers/helm/update/update_handler.go
- module-operator/controllers/module/handlers/helm/upgrade/upgrade_handler.go
Overrides got broken at some point.  This is the fix.
> Fix overrides

- module-operator/controllers/module/finalizer.go
- module-operator/internal/statemachine/tracker.go
- module-operator/internal/statemachine/tracker_test.go
Delete tracker when the CR is deleted.
> VZ-9657 Garbage collection for state machine tracker

- module-operator/controllers/module/handlers/common/base_handler.go
Trivial cleanup of commented-out code
> VZ-9657 remove commented code

- module-operator/manifests/charts/operators/verrazzano-module-operator/.helmignore
- module-operator/manifests/charts/operators/verrazzano-module-operator/Chart.yaml
- module-operator/manifests/charts/operators/verrazzano-module-operator/templates/deployment.yaml
- module-operator/manifests/charts/operators/verrazzano-module-operator/values.yaml
Minor changes to module operator chart.
Remove some values.yaml fields that we don't support.
> VZ-9792 cleanup  module-operator chart

- module-operator/controllers/module/finalizer_test.go
Add  module-operator Finalizer unit tests
> VZ-9610 module-operator Finalizer unit tests

- module-operator/controllers/module/handlers/common/workloads_ready.go
Reverts verrazzano/verrazzano-modules#129
> Revert "Removing leading space from helm key constant"

- tests/modules/helm/lifecycle/lifecycle_suite_test.go
The multiple_instance_lifecycle test runs a bunch of module installs in parallel. They all call the `executeModuleLifecycleOperations` function, which maintains a global map of namespaces and installed modules. Since the test runs in parallel, there is a race condition that can result in a panic due to concurrent updates of the global map.
This PR fixes the race condition by wrapping the map update with a mutex.
> Fix race condition in end-to-end test

- module-operator/apis/platform/v1alpha1/module_types.go
> VZ-9972 update api comments

- module-operator/controllers/module/handlers/helm/install/install_handler.go
- module-operator/controllers/module/handlers/helm/install/install_handler_test.go
- module-operator/controllers/module/handlers/helm/update/update_handler.go
- module-operator/controllers/module/handlers/helm/update/update_handler_test.go
- module-operator/manifests/charts/vz-test/0.1.0/templates/deployment.yaml
- module-operator/manifests/charts/vz-test/0.1.0/values.yaml
For both install and update, allow new changes to be applied while install is in progress.
> VZ-10034 fix update during install

- pkg/kubectlutil/kubectlutil_test.go
Changes to add test for kubectlutil
> VZ-9610: Added kubectlutil test

- module-operator/manifests/charts/vz-test/0.1.0/templates/deployment.yaml
- module-operator/manifests/charts/vz-test/0.1.1/templates/deployment.yaml
- module-operator/manifests/charts/vz-test/0.1.2/templates/deployment.yaml
- pkg/k8s/readiness/daemonset_ready.go
- pkg/k8s/readiness/daemonset_ready_test.go
- pkg/k8s/readiness/deployment_ready.go
- pkg/k8s/readiness/deployment_ready_test.go
- pkg/k8s/readiness/statefulset_ready.go
- pkg/k8s/readiness/statefulset_ready_test.go
- tests/modules/helm/interrupt/interrupt_suite_test.go
- tests/modules/helm/interrupt/update_test.go
Backport of e2e test suite and bug fixes to release/1.6 branch. See #146 for details.
> VZ-9798: End-to-end update interrupt test + bug fixes (#146)

- module-operator/controllers/module/handlers/common/base_handler.go
- module-operator/controllers/module/handlers/common/base_handler_test.go
> VZ-9610 add base handler unit tests

- module-operator/controllers/module/handlers/common/base_handler.go
- module-operator/controllers/module/handlers/common/base_handler_test.go
Cherry pick unit tests to release/1.6
> VZ-9610 add base handler unit tests (#150)

- tests/modules/helm/interrupt/update_test.go
Backport e2e change to release/1.6 branch.
> Shorten the delaySeconds so tests run a little faster (#152)

- tests/modules/helm/lifecycle/lifecycle_suite_test.go
- tests/modules/helm/lifecycle/target_ns_override_lifecycle_test.go
> VZ-9435: test for targetNamespace different than Module namespace(#156)

- tests/modules/helm/interrupt/single_upgrade_test.go
Backport new e2e test to release/1.6 branch.
> VZ-9800: Add e2e upgrade interrupt test (#158)

- pkg/k8s/readiness/pod_ready_test.go
- pkg/kubectlutil/kubectlutil_test.go
PR to backport unit tests added to master branch
> VZ-9610: Added unit tests for module-operator ks8util and pods_ready

- tests/modules/helm/interrupt/multi_upgrade_test.go
- tests/modules/helm/interrupt/update_test.go
Backport new end-to-end test to release/1.6 branch.
> VZ-9808: Add e2e multi upgrade interrupt test (#164)

- .verrazzano-development-version
Change the development version to 1.6.1 so that the image tag is v1.6.1
> Use v1.6.1 image tag

- Jenkinsfile
- Makefile
- make/build.mk
Backport of multi architecture image support to release/1.6 branch. See #167 for details.
> VZ-10084: Add support for multi architecture images (#167)

- pkg/controller/result/builder_test.go
- pkg/controller/result/result.go
- pkg/controller/result/result_test.go
- pkg/helm/repo_test.go
Backport unit tests for result package
> VZ-9610 unit tests for result package

- ignore_copyright_check.txt
- module-operator/apis/platform/v1alpha1/module_types.go
- module-operator/controllers/module/chartutil.go
- module-operator/controllers/module/chartutil_test.go
- module-operator/controllers/module/handlers/multus/factory/factory.go
- module-operator/main.go
- module-operator/manifests/charts/modules/multus/4.0.1/Chart.yaml
- module-operator/manifests/charts/modules/multus/4.0.1/templates/clusterRole.yaml
- module-operator/manifests/charts/modules/multus/4.0.1/templates/configMap.yaml
- module-operator/manifests/charts/modules/multus/4.0.1/templates/crds.yaml
- module-operator/manifests/charts/modules/multus/4.0.1/templates/daemonSets.yaml
- module-operator/manifests/charts/modules/multus/4.0.1/templates/serviceAccount.yaml
- module-operator/manifests/charts/modules/multus/4.0.1/values.yaml
- module-operator/manifests/charts/modules/multus/4.0.2/Chart.yaml
- module-operator/manifests/charts/modules/multus/4.0.2/templates/clusterRole.yaml
- module-operator/manifests/charts/modules/multus/4.0.2/templates/configMap.yaml
- module-operator/manifests/charts/modules/multus/4.0.2/templates/crds.yaml
- module-operator/manifests/charts/modules/multus/4.0.2/templates/daemonSets.yaml
- module-operator/manifests/charts/modules/multus/4.0.2/templates/serviceAccount.yaml
- module-operator/manifests/charts/modules/multus/4.0.2/values.yaml
https://jira.oci.oraclecorp.com/browse/OLCNE-5263
> OLCNE-5263: multus module

- pkg/controller/statemachine/statemachine.go
Log a module done message in statemachine.  Also, only log the module name to reduce noise.
> VZ-10706 log a module done message in statemachine

- module-operator/manifests/charts/modules/calico/3.27.0/Chart.yaml
- module-operator/manifests/charts/modules/calico/3.27.0/values.yaml
fix tigera-operator image name and fixing the versions for calico and the operator.
> fix tigera-operator image name
