verrazzano/verrazzano-modules

module-operator/apis/platform/v1alpha1/modulelifecycle_types.go
module-operator/controllers/modlifecycle/module_lifecycle_controller.go
module-operator/controllers/module/module_controller.go

Use a fake lifecycle class used by the in-operator POC Helm controller; this will help prove out the integration and allow development to continue in parallel.

VZ-9441.  Implement a lifeycycle class for POC helm controller

---

calico-operator/Dockerfile
helm-operator/Dockerfile
module-operator/Dockerfile

Use the latest verrazzano/verrazzano-base image for the verrazzano-modules operator images.

Use Verrazzano base image for operator containers

---

calico-operator/main.go
common/controllers/base/basecontroller/manager.go
common/controllers/lifecycle/manager.go
helm-operator/main.go
module-operator/apis/platform/v1alpha1/modulelifecycle_types.go

This is Mike Cico's code that i integrated into common.
I added calico class to API  types for now.
Have the helm-operator and calico-operator only process ModuleLifecycle CRs with matching lifecycleClass field.
For example, to install calico:
```
apiVersion: platform.verrazzano.io/v1alpha1
kind: ModuleLifecycle
metadata:
name: install
spec:
action: install
lifecycleClass: calico
installer:
helmRelease:
...
```

VZ-9379 add operator to CR binding using class

---

common/controllers/base/basecontroller/controller.go
common/controllers/lifecycle/finalizer.go
common/controllers/lifecycle/manager.go

Change common controller to handle the Finalizer interface.  This provides the foundation for adding Finalizer support to lifecycle operators (when they need it)

VZ-9379 add finalizer support to common controller

---

common/controllers/base/basecontroller/controller.go
common/controllers/base/basecontroller/manager.go
common/controllers/base/spi/controllerspi.go
common/controllers/base/watcher/watcher.go
common/controllers/lifecycle/manager.go

Refactor the common controller and watcher code to minimize the number of watches.  There used to be a watchers per instance of a CR.  Now the watchers are shared for all instances of the CRs.

VZ-9379 minimize the number of watchers

---

common/controllers/base/basecontroller/controller.go
common/controllers/base/basecontroller/controller_test.go
common/controllers/base/spi/controllerspi.go
common/controllers/modulelifecycle/finalizer.go
common/controllers/modulelifecycle/manager.go
common/controllers/modulelifecycle/reconciler.go
module-operator/controllers/module/finalizer.go

Add module common controller unit tests.
Change Finalizer interface to add postFinalizer garbage collection cleanup.  This is needed for tracker map.

VZ-9401 module common controller unit tests

---

module-operator/Dockerfile
module-operator/Makefile
module-operator/manifests/config/scripts/run.sh

This reverts commit 8e44400f0fd4bad716377384ca7c250bff4b7585.
This PR preserves the change to copy the THIRD_PARTY_LICENSES.txt file to the resulting image.

Revert "VZ-9686: Use scratch for operator base image (#95)"

---

module-operator/controllers/module/handlers/common/base_handler.go
module-operator/controllers/module/handlers/helm/install/install_handler.go

When using Helm, set wait to false.  This fixes a regression on a previous commit, 74d9e57ff93182e55591732185ae337f65461c4e

Do Helm wait=false 

---

module-operator/Dockerfile

These changes make installing the `go-toolset` package more robust.

Fix configuring developer repo and installing go-toolset in Dockerfile

---

module-operator/manifests/charts/vz-test/0.1.0/templates/deployment.yaml
module-operator/manifests/charts/vz-test/0.1.0/values.yaml
module-operator/manifests/charts/vz-test/0.1.1/templates/deployment.yaml
module-operator/manifests/charts/vz-test/0.1.1/values.yaml
module-operator/manifests/charts/vz-test/0.1.2/templates/deployment.yaml
module-operator/manifests/charts/vz-test/0.1.2/values.yaml
tests/modules/helm/lifecycle/lifecycle_suite_test.go

added nginx deployment to vz-test `.Values.deployment.delaySeconds` can be overridden to induce delay for interrupt tests
fixed an issue when parallel tests were resulting in intermittent `Operation not permitted` error on module update by updating the latest

VZ-9801: add deployment to vz-test

---

module-operator/controllers/module/handlers/helm/install/install_handler.go
module-operator/controllers/module/handlers/helm/install/install_handler_test.go
pkg/constants/constants.go

Tested this in a local cluster and verified that the namespace is created and labeled correctly.

Create Module targetNamespace if it does not exist

---

module-operator/controllers/module/finalizer_test.go
module-operator/controllers/module/handlers/common/base_handler.go
module-operator/controllers/module/handlers/helm/delete/delete_handler.go
module-operator/controllers/module/handlers/helm/delete/delete_handler_test.go
module-operator/controllers/module/handlers/helm/install/install_handler.go
module-operator/controllers/module/handlers/helm/install/install_handler_test.go
module-operator/controllers/module/handlers/helm/update/update_handler.go
module-operator/controllers/module/handlers/helm/update/update_handler_test.go
module-operator/controllers/module/handlers/helm/upgrade/upgrade_handler.go
module-operator/controllers/module/handlers/helm/upgrade/upgrade_handler_test.go
module-operator/controllers/module/reconciler.go
module-operator/controllers/module/reconciler_test.go
module-operator/internal/handlerspi/handler_context.go
module-operator/internal/handlerspi/statemachine_handler_spi.go
module-operator/internal/statemachine/statemachine.go
module-operator/internal/statemachine/statemachine_test.go

Fix the handler API to be immutable, where the context parameter has CR specific information.
The old handler Init method saved context in the hander, which was shared across all CRs.
This fixes a problem that was exposed during concurrent testing.

Fix handler API to be immutable

---

tests/modules/helm/lifecycle/lifecycle_suite_test.go

The Module createOrUpdate operations were not being retried, and updates would occasionally fail with concurrent update "please retry on the latest version of the resource" errors, so I wrapped that in an `Eventually` so it will be retried on error.
I also improved another `Eventually` to not return bool which results in very little helpful information when the test fails. Now the test will report the specific error if one occurs, or the Module status if it does not match the expected status.

e2e test improvements

---

tests/modules/helm/interrupt/update_test.go

Shorten the startup delay on the e2e interrupt update test. These values still allow us to make module updates while the module is still reconciling and also reduce the total test run time by 10-15 seconds. Reducing the values below these values results in the reconcile completing before the test has a chance to make additional updates to the module.

Shorten the delaySeconds so tests run a little faster

---

module-operator/manifests/charts/operators/verrazzano-module-operator/templates/deployment.yaml
module-operator/manifests/charts/operators/verrazzano-module-operator/values.yaml

The module-operator was using the default port 9100 which conflicts with node-exporter since they both use the host network.  Change the default metrics port to 9110 and make it configurable.

VZ-10059 change default metrics port 9110 

---

module-operator/manifests/charts/operators/verrazzano-module-operator/templates/deployment.yaml
module-operator/manifests/charts/operators/verrazzano-module-operator/values.yaml

Backport  module-operator to use port 9110 for metrics

VZ-10059 default to port 9110 for metrics (#154)

---

tests/modules/helm/interrupt/multi_upgrade_test.go
tests/modules/helm/interrupt/update_test.go

This end-to-end test upgrades the Module multiple times and also updates the values, all while reconciling.
Sample output:
```
=== RUN   TestHelmModuleInterruptTestSuite/TestMultiUpgradeWhileReconciling
update_test.go:80: Installing module default/vz-test-module
update_test.go:117: Waiting for module ready condition to be: True
update_test.go:136: Verifying helm release values
multi_upgrade_test.go:42: Upgrading module to version 0.1.1
update_test.go:88: Updating module values
update_test.go:117: Waiting for module ready condition to be: False
update_test.go:88: Updating module values
multi_upgrade_test.go:55: Upgrading module to version 0.1.2
update_test.go:88: Updating module values
update_test.go:88: Updating module values
update_test.go:117: Waiting for module ready condition to be: …
```

VZ-9808: Add e2e multi upgrade interrupt test

---

Jenkinsfile
Makefile
make/build.mk
module-operator/Dockerfile

This PR adds support for multi architecture images that will run on both amd64 and arm64. CI branch builds by default will build single architecture amd images because multi arch builds take an order of magnitude longer to build. There is a build parameter to override this behavior. Release and main branch builds will always build multi architecture images.
I tested the following:
1. Build locally using the same make targets that we have been using, all works and produces a single architecture amd image
2. Branch build in CI with default settings, produces a single architecture amd image
3. Branch build in CI with multi arch checkbox checked, produces a multi architecture image
4. Installed the multi arch image in a kind cluster running on an M1 Mac, deployed a test Module

VZ-10084: Add support for multi architecture images

---

module-operator/apis/platform/v1alpha1/module_types.go
module-operator/controllers/module/finalizer.go
module-operator/controllers/module/finalizer_test.go
module-operator/controllers/module/manager.go
module-operator/controllers/module/reconciler.go
module-operator/controllers/module/reconciler_test.go
module-operator/controllers/module/status/status.go
module-operator/main.go
module-operator/manifests/charts/operators/verrazzano-module-operator/crds/platform.verrazzano.io_modules.yaml
pkg/controller/base/controllerspi/controllerspi.go
pkg/helm/overrides.go
pkg/helm/overrides_yaml.go

A few changes needed to integrate VPO with modules.
Add ability to specify watch descriptors when creating a controller
Cleanup status updating so it doesn't write condition if no information changed
Add kubebuilder annotations so that kubectl -o wide displays more columns
Make some functions/methods public so that they can be used by VPO

VZ-10309 VPO integration

---

module-operator/controllers/module/finalizer_test.go
module-operator/controllers/module/handlers/helm/install/install_handler_test.go
module-operator/controllers/module/manager.go
module-operator/controllers/module/reconciler.go
module-operator/controllers/module/reconciler_test.go
module-operator/controllers/module/status/status.go
module-operator/controllers/module/watcher.go
module-operator/internal/statemachine/statemachine.go
module-operator/internal/statemachine/tracker.go
pkg/controller/base/basecontroller/controller.go
pkg/controller/base/basecontroller/controller_test.go
pkg/controller/base/basecontroller/manager.go
pkg/controller/base/basecontroller/manager_test.go
pkg/controller/base/basecontroller/types.go
pkg/controller/base/basecontroller/watcher.go
pkg/controller/base/basecontroller/watcher_test.go
pkg/controller/base/controllerspi/controllerspi.go
pkg/controller/result/builder.go
pkg/controller/result/builder_test.go
pkg/controller/result/result_test.go

1. Refactor the base controller watches
2. Each watch context is now per CR Namespaced Names
3. Save latest WatchEvent
4. Add module watch for secrets and configmaps
5. Clean up SPI, add comments
6. Shorten the short requeue delay
7. Change module reconcile to process watch events with generation already matches status generation

VZ-10451 refactor watches and watch configmap and secret

---

module-operator/controllers/module/reconciler.go
module-operator/controllers/module/watcher.go
pkg/controller/base/basecontroller/controller.go
pkg/controller/base/basecontroller/watcher.go
pkg/controller/base/basecontroller/watcher_test.go
pkg/controller/base/controllerspi/controllerspi.go

Cleanup watch SPI, pass in the watch event and a client.  The oldObject is now available to the watcher.

VZ-10544 watch spi - pass in more info to watcher

---

module-operator/controllers/module/reconciler.go

controller-runtime will call reconcile for the same CR concurrently if maxconcurrentreconciles > 1.  Detect this and requeue.

VZ-10544 - prevent concurrent reconcile for same Module CR

---

module-operator/controllers/module/handlers/helm/delete/delete_handler.go
module-operator/controllers/module/handlers/helm/install/install_handler.go
module-operator/controllers/module/handlers/helm/update/update_handler.go
module-operator/controllers/module/handlers/helm/upgrade/upgrade_handler.go
module-operator/controllers/module/reconciler.go
module-operator/controllers/module/reconciler_test.go
pkg/controller/spi/handlerspi/statemachine_handler_spi.go
pkg/controller/statemachine/statemachine.go
pkg/controller/statemachine/statemachine_test.go

Add SPI CheckDependencies call so that we can reduce the likelihood of an update watch forcing a re-reconcile.  This allows us to defer setting the state machine timestamp until after deps are met.  That timestamp is used to determine if a watch should force a reconcile.  If the watch happens after the timestamp then we must re-reconcile.
Also, check if watch occurred during reconciliation so that we know if re-reconcile is needed.

VZ-10544 API CheckDependencies call

---

make/build.mk
module-operator/Dockerfile

Use multi-arch ghcr.io/verrazzano/oraclelinux-golang:v1.20.12 AS build_base. 
Job 4 in https://newbuild.verrazzano.io/job/verrazzano-modules/job/gz%252FOLCNE-5799_go_1.20.12/ has the parameter BUILD_MULTI_ARCH_IMAGES as enabled.

OLCNE-5799 build with golang-1.20.12
